version: '3'
services:
  meme:
    image: shiwuliya/meme:latest
    container_name: meme
    restart: always
    network_mode: "bridge"
    ports:
      - "2244:2244"
    volumes:
      - /opt/meme/data:/data/memes
    environment:
      MEME_DIRS: '["/data/memes"]'
      MEME_DISABLED_LIST: '[]'
      GIF_MAX_SIZE: '10.0'
      GIF_MAX_FRAMES: '100'
      LOG_LEVEL: 'INFO'
      PORT: '2244'
    mem_limit: 1024M
