name: Build and Push Docker Image

on:
  workflow_dispatch:
  push:
    tags:
      - 'release-v*'  

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: 检出代码
      uses: actions/checkout@v3

    - name: 登录 Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: 生成镜像元数据
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}
        tags: |
          type=semver,pattern={{version}},prefix=release-v
          type=semver,pattern=latest,enable={{is_default_branch}}  

    - name: 将标签转换为多行字符串
      id: convert-tags
      run: |
        echo "${{ steps.meta.outputs.tags }}"
        TAGS=$(echo "${{ steps.meta.outputs.tags }}" | jq -r '.[]')
        echo "TAGS=$TAGS" >> $GITHUB_OUTPUT
    - name: 构建并推送 Docker 镜像
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ steps.convert-tags.outputs.TAGS }}
        labels: ${{ steps.meta.outputs.labels }}
