name: Create Release

on:
  push:
    tags:
      - "release-v*"  

permissions:
  contents: write  

jobs:
  create-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Create ZIP Archive
      run: |
        if [ -d "data" ]; then
          zip -r meme.zip data
        else
          echo "目录不存在!" && exit 1
        fi

    - name: Create Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
      run: |
        gh release create ${{ github.ref_name }} meme.zip \
          --title "${{ github.ref_name }}" \
          --notes "${{ github.event.head_commit.message }}"
